spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: Question-service
          uri: lb://QUESTION-SHEET
          predicates:
            - Path=/question/**
          filters:
            - RewritePath=/question/(?<segment>.*), /$\{segment}

        - id: Question-health
          uri: lb://QUESTION-SHEET
          predicates:
            - Path=/question/health
          filters:
            - SetPath=/health

        - id: Resume-service
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/resume/**
          filters:
            - RewritePath=/resume/(?<segment>.*), /$\{segment}

        - id: Resume-health
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/resume/health
          filters:
            - SetPath=/health


      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
            allowedHeaders: "*"
server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true


jwt:
  secret: your-256-bit-secret-key-must-be-at-least-32-characters-long
  expiration: 3600000 # 1 hour
  refreshExpiration: 86400000 # 24 hours